-- Seed default Software Engineer skills
-- Categories: Programming Languages, Web Frontend, Web Backend, Databases,
--             Cloud & DevOps, Data & ML, Mobile, Testing, Security, Systems,
--             Architecture & Design, Soft Skills / Process

INSERT INTO "skills" ("name") VALUES

-- ── Programming Languages ─────────────────────────────────────────────────────
('Python'),
('JavaScript'),
('TypeScript'),
('Java'),
('C'),
('C++'),
('C#'),
('Go'),
('Rust'),
('Ruby'),
('PHP'),
('Swift'),
('Kotlin'),
('Scala'),
('R'),
('Bash / Shell Scripting'),
('PowerShell'),
('Lua'),
('Haskell'),
('Elixir'),
('Erlang'),
('Clojure'),

-- ── Web — Frontend ────────────────────────────────────────────────────────────
('HTML5'),
('CSS3'),
('React'),
('Next.js'),
('Vue.js'),
('Nuxt.js'),
('Angular'),
('Svelte'),
('SvelteKit'),
('Remix'),
('Tailwind CSS'),
('Sass / SCSS'),
('CSS Modules'),
('Webpack'),
('Vite'),
('esbuild'),
('Rollup'),
('Redux'),
('Zustand'),
('Recoil'),
('MobX'),
('TanStack Query'),
('TanStack Table'),
('Framer Motion'),
('Three.js'),
('D3.js'),
('Recharts'),
('Chart.js'),
('WebSockets'),
('WebRTC'),
('Service Workers'),
('Progressive Web Apps'),
('Accessibility (WCAG)'),

-- ── Web — Backend ─────────────────────────────────────────────────────────────
('Node.js'),
('Express.js'),
('Fastify'),
('NestJS'),
('Django'),
('Flask'),
('FastAPI'),
('Ruby on Rails'),
('Laravel'),
('Spring Boot'),
('ASP.NET Core'),
('GraphQL'),
('REST API Design'),
('gRPC'),
('WebSocket Server'),
('OAuth 2.0 / OpenID Connect'),
('JWT'),
('tRPC'),

-- ── Databases ─────────────────────────────────────────────────────────────────
('PostgreSQL'),
('MySQL'),
('SQLite'),
('SQL'),
('MongoDB'),
('Redis'),
('Elasticsearch'),
('DynamoDB'),
('Cassandra'),
('Neo4j'),
('CockroachDB'),
('Supabase'),
('PlanetScale'),
('Prisma'),
('Drizzle ORM'),
('SQLAlchemy'),
('Hibernate'),
('Database Design'),
('Query Optimization'),
('Data Modeling'),

-- ── Cloud & DevOps ────────────────────────────────────────────────────────────
('AWS'),
('GCP'),
('Azure'),
('Docker'),
('Kubernetes'),
('Terraform'),
('Ansible'),
('Pulumi'),
('GitHub Actions'),
('GitLab CI/CD'),
('CircleCI'),
('Jenkins'),
('Helm'),
('Linux'),
('Nginx'),
('Apache'),
('Cloudflare'),
('Vercel'),
('Netlify'),
('Heroku'),
('Railway'),
('Serverless / Lambda'),
('CDN'),
('Load Balancing'),
('Infrastructure as Code'),
('Site Reliability Engineering'),
('Observability'),
('Prometheus'),
('Grafana'),
('OpenTelemetry'),
('Datadog'),

-- ── Data & ML ─────────────────────────────────────────────────────────────────
('Machine Learning'),
('Deep Learning'),
('Natural Language Processing'),
('Computer Vision'),
('PyTorch'),
('TensorFlow'),
('Keras'),
('scikit-learn'),
('Hugging Face Transformers'),
('LangChain'),
('OpenAI API'),
('Pandas'),
('NumPy'),
('Matplotlib'),
('Jupyter Notebooks'),
('Spark'),
('Kafka'),
('Airflow'),
('dbt'),
('Snowflake'),
('BigQuery'),
('Data Warehousing'),
('ETL Pipelines'),
('Feature Engineering'),
('Model Evaluation'),
('MLflow'),
('Vector Databases'),

-- ── Mobile ────────────────────────────────────────────────────────────────────
('React Native'),
('Flutter'),
('iOS Development'),
('Android Development'),
('SwiftUI'),
('Jetpack Compose'),
('Expo'),
('App Store Deployment'),

-- ── Testing ───────────────────────────────────────────────────────────────────
('Unit Testing'),
('Integration Testing'),
('End-to-End Testing'),
('Test-Driven Development'),
('Jest'),
('Vitest'),
('Playwright'),
('Cypress'),
('Selenium'),
('PyTest'),
('JUnit'),
('Mock / Stub / Spy'),
('Load Testing'),
('Performance Testing'),

-- ── Security ──────────────────────────────────────────────────────────────────
('Application Security'),
('OWASP Top 10'),
('Penetration Testing'),
('Static Analysis (SAST)'),
('Dependency Scanning'),
('Secret Management'),
('Encryption'),
('Zero Trust Architecture'),
('SOC 2 Compliance'),
('Security Clearance — TS/SCI'),
('Security Clearance — Secret'),

-- ── Systems & Networking ──────────────────────────────────────────────────────
('Operating Systems'),
('Networking (TCP/IP)'),
('Concurrency & Parallelism'),
('Memory Management'),
('Embedded Systems'),
('FPGA'),
('Compiler Design'),
('Assembly'),
('Protocol Buffers'),
('Message Queues'),
('RabbitMQ'),

-- ── Architecture & Design ─────────────────────────────────────────────────────
('System Design'),
('Microservices'),
('Event-Driven Architecture'),
('Domain-Driven Design'),
('CQRS / Event Sourcing'),
('API Gateway'),
('Design Patterns'),
('Clean Architecture'),
('Distributed Systems'),
('High Availability Design'),
('Performance Optimization'),
('Caching Strategies'),

-- ── Version Control & Collaboration ──────────────────────────────────────────
('Git'),
('GitHub'),
('GitLab'),
('Code Review'),
('Monorepo'),
('Semantic Versioning'),

-- ── Process & Soft Skills ─────────────────────────────────────────────────────
('Agile / Scrum'),
('Kanban'),
('Technical Writing'),
('Mentoring'),
('Cross-Functional Collaboration'),
('Stakeholder Communication'),
('Problem Solving'),
('Debugging')

ON CONFLICT ON CONSTRAINT skills_name_unique DO NOTHING;
