-- Company career metadata enrichment
-- Generated 2026-08-01 from the attached exact company-name list.
-- website is intentionally NULL when no official career page returned HTTP 2xx/3xx after redirects.
-- NULL HQ/industry values preserve existing database values; they do not erase prior enrichment.
-- HTTPS-only is intentional: insecure HTTP career links are treated as unavailable.
-- Exact, case-sensitive names are intentional because this is a one-time update from a database export.
-- Do not fuzzy-match aliases here: the unmatched-company query exposes drift without risking a wrong update.

BEGIN;

CREATE TEMP TABLE company_career_metadata (
  name text PRIMARY KEY,
  website text,
  hq_location text,
  industry text,
  CHECK (website IS NULL OR website ~ '^https://')
) ON COMMIT DROP;

INSERT INTO company_career_metadata (name, website, hq_location, industry)
VALUES
  ('Amazon Web Services (AWS)', 'https://aws.amazon.com/careers/', 'Seattle, WA', 'Cloud Computing'),
  ('Deloitte', 'https://www.deloitte.com/global/en/careers/job-search.html', 'London, UK', 'Professional Services'),
  ('Lockheed Martin', 'https://www.lockheedmartin.com/en-us/careers/', 'Bethesda, MD', 'Aerospace and Defense'),
  ('Booz Allen Hamilton', 'https://www.boozallen.com/careers.html', 'McLean, VA', 'Management Consulting'),
  ('Alignerr', 'https://www.alignerr.com/jobs', NULL, NULL),
  ('Google', 'https://www.google.com/about/careers/applications/', 'Mountain View, CA', 'Technology'),
  ('Vantor', 'https://vantor.com/careers/', NULL, NULL),
  ('Salesforce', 'https://www.salesforce.com/company/careers/', 'San Francisco, CA', 'Enterprise Software'),
  ('Colorado Aviation Business Association (CABA)', NULL, NULL, NULL),
  ('CACI International Inc', 'https://careers.caci.com/', 'Reston, VA', 'Defense and Government Technology'),
  ('Blue Origin', 'https://www.blueorigin.com/careers/search', 'Kent, WA', 'Aerospace'),
  ('Northrop Grumman', 'https://www.northropgrumman.com/careers', 'Falls Church, VA', 'Aerospace and Defense'),
  ('Sierra Space', NULL, 'Louisville, CO', 'Aerospace'),
  ('Raytheon', 'https://careers.rtx.com/global/en', 'Arlington, VA', 'Aerospace and Defense'),
  ('Scribd, Inc.', NULL, NULL, NULL),
  ('Cisco', 'https://www.cisco.com/careers/', 'San Jose, CA', 'Networking Technology'),
  ('Workday', 'https://www.workday.com/en-us/company/careers/overview.html', 'Pleasanton, CA', 'Enterprise Software'),
  ('Ibotta', 'https://ibotta.com/work-with-us/careers', 'Denver, CO', 'Financial Technology'),
  ('EchoStar Corporation', NULL, NULL, NULL),
  ('Quindar', 'https://quindar.space/careers/', NULL, NULL),
  ('SciTec', NULL, NULL, NULL),
  ('PwC', 'https://www.pwc.com/us/en/careers.html', NULL, NULL),
  ('HDR', 'https://www.hdrinc.com/careers', NULL, NULL),
  ('PNC Financial Services Group', 'https://careers.pnc.com/global/en', 'Pittsburgh, PA', 'Financial Services'),
  ('Transamerica', 'https://www.transamerica.com/careers', 'Cedar Rapids, IA', 'Financial Services'),
  ('Inceed', 'https://jobs.inceed.com/job-seekers/', NULL, NULL),
  ('Lynx', NULL, NULL, NULL),
  ('Judi Health', NULL, NULL, NULL),
  ('Prologis', 'https://www.prologis.com/about/careers', 'San Francisco, CA', 'Logistics Real Estate'),
  ('Sierra Nevada Corporation', 'https://www.sncorp.com/careers/', 'Sparks, NV', 'Aerospace and Defense'),
  ('EY', 'https://www.ey.com/en_gl/careers', 'London, UK', 'Professional Services'),
  ('Affirm', 'https://www.affirm.com/careers', 'San Francisco, CA', 'Financial Technology'),
  ('LG Ad Solutions', 'https://lgads.tv/careers/', NULL, NULL),
  ('EVONA', 'https://evona.com/jobs/', NULL, NULL),
  ('VIZIO', 'https://careers.walmart.com/us/en/home/vizio', 'Irvine, CA', 'Consumer Electronics'),
  ('Crusoe', 'https://www.crusoe.ai/about/careers', NULL, NULL),
  ('KPMG US', 'https://www.kpmguscareers.com/', 'New York, NY', 'Professional Services'),
  ('Gusto', NULL, 'San Francisco, CA', 'Human Resources Software'),
  ('Empower', 'https://jobs.empower.com/', NULL, NULL),
  ('Accenture', 'https://www.accenture.com/us-en/careers', 'Dublin, Ireland', 'Professional Services'),
  ('Altamira Technologies Corporation', NULL, NULL, NULL),
  ('AppFolio', 'https://www.appfolio.com/company/careers', 'Santa Barbara, CA', 'Property Management Software'),
  ('Litera', 'https://www.litera.com/careers', NULL, NULL),
  ('TALENT Software Services', NULL, NULL, NULL),
  ('hackajob', 'https://hackajob.com/jobs', NULL, NULL),
  ('bet365', 'https://www.bet365careers.com/', 'Stoke-on-Trent, UK', 'Online Gambling'),
  ('Atom Computing', 'https://atom-computing.com/careers/', NULL, NULL),
  ('U.S. Bank', 'https://careers.usbank.com/global/en', 'Minneapolis, MN', 'Financial Services'),
  ('Worldpay', 'https://jobs.globalpayments.com/', 'Cincinnati, OH', 'Payment Processing'),
  ('Raytheon Australia', NULL, NULL, NULL),
  ('Vertafore', 'https://www.vertafore.com/about/join-our-team', NULL, NULL),
  ('Leidos', 'https://www.leidos.com/careers/life', 'Reston, VA', 'Defense and Information Technology'),
  ('Energy Acuity', 'https://www.enverus.com/careers/', NULL, NULL),
  ('Protingent', 'https://jobs.protingent.com/', NULL, NULL),
  ('SMX', 'https://www.smxtech.com/careers/', NULL, NULL),
  ('BAE Systems, Inc.', 'https://jobs.baesystems.com/global/en', 'Falls Church, VA', 'Aerospace and Defense'),
  ('NVIDIA', 'https://www.nvidia.com/en-us/about-nvidia/careers/', 'Santa Clara, CA', 'Semiconductors and Artificial Intelligence'),
  ('DAT Freight & Analytics', 'https://careers.dat.com/', NULL, NULL),
  ('Colorado AI News', NULL, NULL, NULL),
  ('Trace3', NULL, NULL, NULL),
  ('Stored Energy Systems LLC (SENS)', NULL, NULL, NULL),
  ('Sitetracker', 'https://www.sitetracker.com/company/careers/', NULL, NULL),
  ('Qualis1 Inc.', NULL, NULL, NULL),
  ('EY-Parthenon', NULL, NULL, NULL),
  ('KaiHonua', 'https://www.kaihonua.com/careers', NULL, NULL),
  ('Bayview Asset Management, LLC', NULL, NULL, NULL),
  ('Rincon Research Corporation', NULL, NULL, NULL),
  ('High Country Search Group', NULL, NULL, NULL),
  ('American Family Insurance', NULL, 'Madison, WI', 'Insurance'),
  ('Autonomous Solutions, Inc. (ASI)', NULL, NULL, NULL),
  ('DISH TV', NULL, 'Englewood, CO', 'Telecommunications'),
  ('Yes Energy Demand Forecasts', NULL, NULL, NULL),
  ('Apex Systems', 'https://www.apexsystems.com/careers', NULL, NULL),
  ('Compa', NULL, NULL, NULL),
  ('Crocs, Inc.', NULL, 'Broomfield, CO', 'Footwear'),
  ('Clera', NULL, NULL, NULL),
  ('DaVita Kidney Care', 'https://careers.davita.com/', 'Denver, CO', 'Healthcare'),
  ('Haystack', NULL, NULL, NULL),
  ('Vorto', 'https://vorto.ai/careers/', NULL, NULL),
  ('ZOLL Medical Corporation', 'https://careers.zoll.com/', NULL, NULL),
  ('Anduril Industries', 'https://www.anduril.com/careers', 'Costa Mesa, CA', 'Defense Technology'),
  ('Offstream', NULL, NULL, NULL),
  ('University of Colorado', 'https://www.cu.edu/cu-careers', 'Denver, CO', 'Higher Education'),
  ('Antech Diagnostics', 'https://www.antechdiagnostics.com/in-house-diagnostics/careers/', NULL, NULL),
  ('Pearson', 'https://pearson.jobs/', 'London, UK', 'Education'),
  ('Parsons Corporation', 'https://jobs.parsons.com/', NULL, NULL),
  ('Jerry', NULL, NULL, NULL),
  ('Trimble Inc.', 'https://www.trimble.com/en/careers', 'Westminster, CO', 'Industrial Technology'),
  ('Loft Orbital', 'https://loftorbital.com/careers/', NULL, NULL),
  ('Alarm.com', 'https://alarm.com/careers', NULL, NULL),
  ('Slalom', 'https://www.slalom.com/us/en/careers', NULL, NULL),
  ('Zayo Group', 'https://www.zayo.com/careers/', 'Boulder, CO', 'Telecommunications'),
  ('Lunar Outpost', 'https://www.lunaroutpost.com/careers', NULL, NULL),
  ('Eli Lilly and Company', 'https://careers.lilly.com/us/en', 'Indianapolis, IN', 'Pharmaceuticals'),
  ('Iterable', 'https://iterable.com/careers/', NULL, NULL),
  ('Checkr, Inc.', 'https://checkr.com/company/careers', NULL, NULL),
  ('Medtronic', 'https://www.medtronic.com/en-us/our-company/careers.html', 'Galway, Ireland', 'Medical Devices'),
  ('Terumo Blood and Cell Technologies', 'https://www.terumobct.com/en/gl/our-company/careers.html', NULL, NULL),
  ('Global Payments Inc.', NULL, NULL, NULL),
  ('CoorsTek, Inc.', NULL, NULL, NULL),
  ('Lynker', 'https://careers-lynker.icims.com/jobs/search?hashed=-625884911&mobile=false&width=1286&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240', NULL, NULL),
  ('CitiusTech', 'https://www.citiustech.com/careers', NULL, NULL),
  ('Keysight Technologies', 'https://jobs.keysight.com/external', 'Santa Rosa, CA', 'Electronic Test and Measurement'),
  ('Nametag', NULL, NULL, NULL),
  ('Quantinuum', 'https://www.quantinuum.com/company/careers', NULL, NULL),
  ('Spire', NULL, NULL, NULL),
  ('Infleqtion', 'https://infleqtion.com/careers/', NULL, NULL),
  ('Red Oak Technologies', 'https://redoaktech.com/careers/', NULL, NULL),
  ('State of Colorado', 'https://careers.colorado.gov/', 'Denver, CO', 'Government'),
  ('ENVISION ENERGY USA LTD', NULL, NULL, NULL),
  ('CoBank', 'https://www.cobank.com/careers', 'Greenwood Village, CO', 'Financial Services'),
  ('Housecall Pro', 'https://www.housecallpro.com/careers/', NULL, NULL),
  ('Yes Energy', 'https://www.yesenergy.com/careers', NULL, NULL),
  ('York Space Systems', 'https://recruitingbypaycor.com/career/CareerHome.action?clientId=8a7883d0821e1a6301823c22a8bd068b', NULL, NULL),
  ('Arcfield', 'https://careers.arcfield.com/careers-home', NULL, NULL),
  ('Cleerly', 'https://cleerly.com/careers', NULL, NULL),
  ('MYR Group', 'https://careers.myrgroup.com/', NULL, NULL),
  ('Homebot', NULL, NULL, NULL),
  ('STR', NULL, NULL, NULL),
  ('Calance', 'https://www.calanceus.com/careers', NULL, NULL),
  ('Nickerson Talent Solutions', NULL, NULL, NULL),
  ('AspenView Technology Partners', NULL, NULL, NULL),
  ('Jobot', NULL, NULL, NULL),
  ('Lyra Technology Group', 'https://lyratechgroup.com/careers/', NULL, NULL),
  ('DAT', 'https://careers.dat.com/', NULL, NULL),
  ('Ascend Analytics', 'https://www.ascendanalytics.com/about-us/careers', NULL, NULL),
  ('School District 27J', NULL, NULL, NULL),
  ('University of Colorado Boulder', 'https://www.colorado.edu/jobs', NULL, NULL),
  ('Revel IT', 'https://www.revelit.com/internal-careers/', NULL, NULL),
  ('CONMED Corporation', NULL, NULL, NULL),
  ('All Copy Products', NULL, NULL, NULL),
  ('Senior Python', NULL, NULL, NULL),
  ('Cisco Systems', 'https://www.cisco.com/careers/', 'San Jose, CA', 'Networking Technology'),
  ('KBR Careers', 'https://careers.kbr.com/us/en', NULL, NULL),
  ('Varmoda', NULL, NULL, NULL),
  ('Sovrn', 'https://www.sovrn.com/careers/', NULL, NULL),
  ('Executive Recruiting Group', NULL, NULL, NULL),
  ('Watershed', 'https://watershed.com/careers', NULL, NULL),
  ('TeamLogic IT', NULL, NULL, NULL),
  ('Engine', NULL, NULL, NULL),
  ('CoreSite', 'https://www.coresite.com/about/careers', NULL, NULL),
  ('Stantec', 'https://www.stantec.com/careers', NULL, NULL),
  ('Axle Collective', NULL, NULL, NULL),
  ('Husch Blackwell', 'https://www.huschblackwell.com/careers', NULL, NULL),
  ('Frontdoor, Inc.', NULL, NULL, NULL),
  ('BW Design Group', NULL, NULL, NULL),
  ('Unit8', NULL, NULL, NULL),
  ('EverDriven', NULL, NULL, NULL),
  ('ATEC Spine', 'https://atecspine.com/careers/', NULL, NULL),
  ('ClifyX', 'https://clifyx.com/career/', NULL, NULL),
  ('Bitflip Engineering', NULL, NULL, NULL),
  ('R Systems', 'https://www.rsystems.com/join-us/', NULL, NULL),
  ('Insight Global', 'https://insightglobal.com/jobs', NULL, NULL),
  ('Homebase', 'https://www.joinhomebase.com/careers', NULL, NULL),
  ('KBI Biopharma', 'https://www.kbibiopharma.com/careers', NULL, NULL),
  ('Ledgent Technology', NULL, NULL, NULL),
  ('Autodesk', 'https://www.autodesk.com/careers/overview', 'San Francisco, CA', 'Design Software'),
  ('SecurityScorecard', 'https://securityscorecard.com/company/careers/', NULL, NULL),
  ('Medpace', NULL, NULL, NULL),
  ('Connect for Health Colorado', NULL, NULL, NULL),
  ('Mark VII - Clean Cars®', NULL, NULL, NULL),
  ('Spectrum', 'https://jobs.spectrum.com/', NULL, NULL),
  ('ChatGPT Jobs', NULL, NULL, NULL),
  ('FOTOMILL STUDIOS LIMITED', NULL, NULL, NULL),
  ('Clay', NULL, NULL, NULL),
  ('Canals', NULL, NULL, NULL),
  ('Sherpa 6, Inc.', NULL, NULL, NULL),
  ('3LC.AI', NULL, NULL, NULL),
  ('Zachary Piper Solutions', 'https://careers.zacharypiper.com/', NULL, NULL),
  ('Kharon', 'https://www.kharon.com/careers', NULL, NULL),
  ('Sony', 'https://www.sonyjobs.com/', 'Tokyo, Japan', 'Technology and Entertainment'),
  ('ConsultNet Technology Services and Solutions', NULL, NULL, NULL),
  ('DRS IT Solutions Inc', NULL, NULL, NULL),
  ('Spectra Logic', 'https://spectralogic.com/company/careers/', NULL, NULL),
  ('SWIFT HIRE LLC', NULL, NULL, NULL),
  ('UPS', 'https://www.jobs-ups.com/us/en', 'Atlanta, GA', 'Logistics'),
  ('Evio', NULL, NULL, NULL),
  ('Access Data Consulting Corporation', NULL, NULL, NULL),
  ('Signifyd', 'https://www.signifyd.com/careers/', NULL, NULL),
  ('IBM', 'https://www.ibm.com/careers', 'Armonk, NY', 'Technology and Consulting'),
  ('Visa U.S.A. Inc.', 'https://corporate.visa.com/en/careers.html', 'San Francisco, CA', 'Payment Technology'),
  ('STACK Infrastructure', 'https://www.stackinfra.com/about/careers/', NULL, NULL),
  ('UDR', 'https://www.udr.com/careers', NULL, NULL),
  ('The GEO Group', 'https://www.geogroup.com/careers', NULL, NULL),
  ('Micron Technology', 'https://www.micron.com/about/careers', 'Boise, ID', 'Semiconductors'),
  ('GlobalLogic', 'https://www.globallogic.com/careers/', NULL, NULL),
  ('CommonSpirit Health', 'https://www.commonspirit.careers/', 'Chicago, IL', 'Healthcare'),
  ('Cubby Beds', 'https://cubbybeds.com/pages/careers', NULL, NULL),
  ('EisnerAmper', 'https://careers.eisneramper.com/', NULL, NULL),
  ('Axos Bank', 'https://www.axosbank.com/careers', NULL, NULL),
  ('AIR Communities', 'https://www.aircommunities.com/en/career-home/careers-overview.html', NULL, NULL),
  ('PDS', NULL, NULL, NULL),
  ('T-Mobile', 'https://careers.t-mobile.com/', 'Bellevue, WA', 'Telecommunications'),
  ('Straddle', 'https://straddle.pro/careers', NULL, NULL),
  ('The Home Depot', 'https://careers.homedepot.com/job-search-results/', 'Atlanta, GA', 'Retail'),
  ('Maybern', 'https://www.maybern.com/careers', NULL, NULL),
  ('Appian', 'https://careers.appian.com/', NULL, NULL),
  ('Compri Consulting', 'https://compri.com/apply-for-jobs/', NULL, NULL),
  ('Bank of America', 'https://careers.bankofamerica.com/en-us', 'Charlotte, NC', 'Financial Services'),
  ('Particle Measuring Systems', 'https://www.pmeasuring.com/careers/', NULL, NULL),
  ('Yield Solutions Group', 'https://yieldsolutionsgroup.com/careers', NULL, NULL),
  ('Motorola Solutions', 'https://www.motorolasolutions.com/en_us/about/careers.html', NULL, NULL),
  ('NextGen | GTA: A Kelly Telecom Company', NULL, NULL, NULL),
  ('ECLARO', 'https://www.careers-eclaro.com/', NULL, NULL),
  ('Microsoft', 'https://careers.microsoft.com/v2/global/en/home.html', 'Redmond, WA', 'Technology'),
  ('Symhas', NULL, NULL, NULL),
  ('Local Hero', NULL, NULL, NULL),
  ('NBCUniversal', 'https://www.nbcuniversal.com/careers', NULL, NULL),
  ('DeNOVO Solutions, LLC', NULL, NULL, NULL),
  ('Meta', 'https://www.metacareers.com/jobsearch/', 'Menlo Park, CA', 'Technology'),
  ('Denver Health', 'https://www.denverhealth.org/for-professionals/careers', NULL, NULL),
  ('Expedite Talent Solutions', NULL, NULL, NULL),
  ('VetJobs', 'https://vetjobs.org/careers/', NULL, NULL),
  ('Rocket Lab', NULL, NULL, NULL),
  ('Nestlé Purina', 'https://www.nestlejobs.com/nestle-purina', NULL, NULL),
  ('AMERICAN SYSTEMS', 'https://www.americansystems.com/careers', NULL, NULL),
  ('Simplesense', NULL, NULL, NULL),
  ('EITACIES Inc.', NULL, NULL, NULL),
  ('Tyler Technologies', 'https://www.tylertech.com/careers', NULL, NULL),
  ('Cherry Bekaert', 'https://careers.cbh.com/', NULL, NULL),
  ('GigFinder.ai', NULL, NULL, NULL),
  ('Fresher Door', NULL, NULL, NULL),
  ('Mechanics Bank', 'https://www.mechanicsbank.com/about-us/careers/joining-mechanics-bank/', NULL, NULL),
  ('Global Resource Design Inc', NULL, NULL, NULL),
  ('Zero Homes', 'https://jobs.lever.co/zerohomes/', NULL, NULL),
  ('CFS', NULL, NULL, NULL),
  ('BDO USA', 'https://www.bdo.com/careers', NULL, NULL),
  ('KellyMitchell Group', 'https://www.careers.kellymitchell.com/', NULL, NULL),
  ('BillingPlatform', 'https://billingplatform.com/company/careers', NULL, NULL),
  ('DataAnnotation', NULL, NULL, NULL),
  ('Tallgrass', NULL, NULL, NULL),
  ('ROLINC Staffing', 'https://jobs.rolinc.com/', NULL, NULL),
  ('Kforce Inc', NULL, NULL, NULL),
  ('Outrider', NULL, NULL, NULL),
  ('Ready Foods Inc.', NULL, NULL, NULL),
  ('Accenture Federal Services', 'https://www.accenture.com/us-en/careers/local/federal-careers', NULL, NULL),
  ('Datadog', 'https://careers.datadoghq.com/', 'New York, NY', 'Cloud Monitoring Software'),
  ('TechInsights', 'https://techinsights.com/about-techinsights/overview/careers-techinsights', NULL, NULL),
  ('ICR, Inc.', 'https://icrinc.com/careers/', NULL, NULL),
  ('Amplify.LA', 'https://amplify.la/jobs/', NULL, NULL),
  ('Veho', 'https://www.shipveho.com/careers', NULL, NULL),
  ('IDR, Inc.', 'https://www.idr-inc.com/careers/', NULL, NULL),
  ('Software Technology Inc.', NULL, NULL, NULL),
  ('Sentar Inc.', NULL, NULL, NULL),
  ('Hunter Douglas, Inc.', NULL, NULL, NULL),
  ('Circadence', 'https://circadence.com/careers/', NULL, NULL),
  ('Strava', 'https://www.strava.com/careers', NULL, NULL),
  ('TTEC', 'https://www.ttecjobs.com/en', NULL, NULL),
  ('Intelligems', 'https://www.intelligems.io/company/careers', NULL, NULL),
  ('Trilyon, Inc.', NULL, NULL, NULL),
  ('Sectra', 'https://career.sectra.com/', NULL, NULL),
  ('Exclusive Resorts', NULL, NULL, NULL),
  ('Analytic Partners', 'https://analyticpartners.com/about/careers/', NULL, NULL),
  ('HP', 'https://jobs.hp.com/', NULL, NULL),
  ('National Laboratory of the Rockies', NULL, NULL, NULL),
  ('NetApp', 'https://careers.netapp.com/', NULL, NULL),
  ('Pylon', NULL, NULL, NULL),
  ('Raymond James', NULL, NULL, NULL),
  ('Chalk', NULL, NULL, NULL),
  ('Orica', NULL, NULL, NULL),
  ('SimpleSUB Water', NULL, NULL, NULL),
  ('Aidoc', 'https://www.aidoc.com/about/careers/', NULL, NULL),
  ('Opichi', 'https://www.opichi.com/careers', NULL, NULL),
  ('Blue Signal Search', 'https://bluesignal.com/search-jobs/', NULL, NULL),
  ('Harris Computer', 'https://www.harriscomputer.com/careers', NULL, NULL),
  ('Kiewit', 'https://www.kiewit.com/careers/', NULL, NULL),
  ('Adalta', NULL, NULL, NULL),
  ('Ria Money Transfer', NULL, NULL, NULL),
  ('TaskRay', NULL, NULL, NULL),
  ('Arete', NULL, NULL, NULL),
  ('Deepgram', 'https://deepgram.com/careers', NULL, NULL),
  ('Golden Aluminum', 'https://goldenaluminum.com/careers', NULL, NULL),
  ('Hudson River Trading', 'https://www.hudsonrivertrading.com/careers/', NULL, NULL),
  ('RingCentral', 'https://www.ringcentral.com/company/careers/overview.html', NULL, NULL),
  ('GIRRAPHIC', NULL, NULL, NULL),
  ('Deep Reef', NULL, NULL, NULL),
  ('Boom Supersonic', 'https://boomsupersonic.com/careers', NULL, NULL),
  ('Ulteig', 'https://ulteig.com/careers/', NULL, NULL),
  ('DESRI', 'https://desri.com/careers/', NULL, NULL),
  ('Intellivation', NULL, NULL, NULL),
  ('AutoStore™', 'https://www.autostoresystem.com/careers', NULL, NULL),
  ('Zimmer Biomet', 'https://careers.zimmerbiomet.com/us/en', NULL, NULL),
  ('Volley Automation', 'https://volleyautomation.com/careers/', NULL, NULL),
  ('IT Engagements, Inc.', NULL, NULL, NULL),
  ('Astreya', 'https://astreya.com/about-us/careers', NULL, NULL),
  ('d.wilson mfg', NULL, NULL, NULL),
  ('Ampstek', 'https://www.ampstek.com/careers', NULL, NULL),
  ('Witbe', 'https://www.witbe.net/careers/', NULL, NULL),
  ('PNC', NULL, NULL, NULL),
  ('Seneca Holdings', 'https://senecaholdings.com/careers/', NULL, NULL),
  ('ClickHouse', 'https://clickhouse.com/company/careers', NULL, NULL),
  ('Crowe', 'https://careers.crowe.com/', NULL, NULL),
  ('CapTech', 'https://www.captechconsulting.com/careers', NULL, NULL),
  ('Boulder Biologics Research Center', NULL, NULL, NULL),
  ('Quantum', NULL, NULL, NULL),
  ('AtkinsRéalis', 'https://careers.atkinsrealis.com/en', NULL, NULL),
  ('SPECTRUM', 'https://jobs.spectrum.com/', NULL, NULL),
  ('GliaCell Technologies', NULL, NULL, NULL),
  ('Tract Capital Management', NULL, NULL, NULL),
  ('Campminder', 'https://campminder.com/careers/', NULL, NULL),
  ('Vizient, Inc', 'https://www.vizient.com/company/careers', NULL, NULL),
  ('Uplight', 'https://uplight.com/careers/', NULL, NULL),
  ('Forge', NULL, NULL, NULL),
  ('Colorado Department of Public Health and Environment', NULL, NULL, NULL),
  ('Garmin', 'https://www.garmin.com/en-US/careers/', NULL, NULL),
  ('TherapyNotes.com', 'https://www.therapynotes.com/careers/', NULL, NULL),
  ('Melco International, LLC', NULL, NULL, NULL),
  ('Nasdaq', 'https://www.nasdaq.com/about/careers', NULL, NULL),
  ('Brooksource', 'https://www.brooksource.com/jobs', NULL, NULL),
  ('Bluestaq', 'https://www.bluestaq.com/careers', NULL, NULL),
  ('Candid Health', 'https://candidhealth.com/careers', NULL, NULL),
  ('SET Development', NULL, NULL, NULL),
  ('Yext', 'https://www.yext.com/careers', NULL, NULL),
  ('Infinite Computer Solutions', 'https://www.infinite.com/careers', NULL, NULL),
  ('TIFIN', 'https://tifin.com/careers/', NULL, NULL),
  ('Legora', NULL, NULL, NULL),
  ('RVO Health', 'https://www.rvohealth.com/careers', NULL, NULL),
  ('The GEO Group, Inc.', 'https://www.geogroup.com/careers', NULL, NULL),
  ('Amazon', 'https://amazon.jobs/en/', 'Seattle, WA', 'E-commerce and Cloud Computing'),
  ('FareHarbor', 'https://fareharbor.com/careers/', NULL, NULL),
  ('IMA Financial Group, Inc.', NULL, NULL, NULL),
  ('AMD', 'https://www.amd.com/en/corporate/careers.html?utm_campaign=careers&utm_medium=redirect&utm_source=301', 'Santa Clara, CA', 'Semiconductors'),
  ('Advanced Space', 'https://advancedspace.com/careers/', NULL, NULL),
  ('Meltwater', 'https://www.meltwater.com/en/careers', NULL, NULL),
  ('Revolution Technologies, LLC', NULL, NULL, NULL),
  ('Emonics LLC', NULL, NULL, NULL),
  ('Proofpoint', 'https://www.proofpoint.com/us/company/careers', NULL, NULL),
  ('Oculus Systems Security', NULL, NULL, NULL),
  ('MKS Inc.', NULL, NULL, NULL),
  ('Palo Alto Networks', 'https://jobs.paloaltonetworks.com/en', 'Santa Clara, CA', 'Cybersecurity'),
  ('The Trade Desk', 'https://careers.thetradedesk.com/', 'Ventura, CA', 'Advertising Technology'),
  ('Horizontal Talent', NULL, NULL, NULL),
  ('Comcast', 'https://jobs.comcast.com/', 'Philadelphia, PA', 'Telecommunications and Media'),
  ('Seagate Technology', 'https://www.seagate.com/careers', 'Fremont, CA', 'Data Storage'),
  ('Katalyst Space', NULL, NULL, NULL),
  ('bp', 'https://careers.bp.com/', 'London, UK', 'Energy'),
  ('Electro Magnetic Applications, Inc.', NULL, NULL, NULL),
  ('TEKsystems', 'https://www.teksystems.com/careers', NULL, NULL),
  ('Salve.Lab', NULL, NULL, NULL),
  ('Planisware', 'https://careers.planisware.com/en/', NULL, NULL),
  ('Figma', 'https://www.figma.com/careers/', 'San Francisco, CA', 'Design Software');

-- Review names absent from the target database before committing.
SELECT m.name AS unmatched_company
FROM company_career_metadata AS m
LEFT JOIN companies AS c ON c.name = m.name
WHERE c.id IS NULL
ORDER BY m.name;

UPDATE companies AS c
SET
  website = m.website,
  hq_location = COALESCE(m.hq_location, c.hq_location),
  industry = COALESCE(m.industry, c.industry)
FROM company_career_metadata AS m
WHERE c.name = m.name
  AND (c.website, c.hq_location, c.industry)
      IS DISTINCT FROM
      (m.website, COALESCE(m.hq_location, c.hq_location), COALESCE(m.industry, c.industry));

-- Post-update summary; website NULL means no verified official career page was available.
SELECT
  COUNT(*) AS attached_names,
  COUNT(*) FILTER (WHERE website IS NOT NULL) AS verified_career_pages,
  COUNT(*) FILTER (WHERE website IS NULL) AS blank_career_pages,
  COUNT(*) FILTER (WHERE hq_location IS NOT NULL) AS supplied_hq_locations,
  COUNT(*) FILTER (WHERE industry IS NOT NULL) AS supplied_industries
FROM company_career_metadata;

COMMIT;
